sudo: required
services:
  - docker

after_success:
  - docker build -t mengzhou44/multi-client  ./client
  - docker build -t mengzhou44/multi-nginx   ./nginx
  - docker build -t mengzhou44/multi-server  ./server
  - docker build -t mengzhou44/multi-worker  ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
  - docker push mengzhou44/multi-client
  - docker push mengzhou44/multi-nginx
  - docker push mengzhou44/multi-server
  - docker push mengzhou44/multi-worker
